on: push
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          tags: amh9412/git-actions-test:latest
      - name: deploy to cluster
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f /home/ubuntu/git-actions-test/my_app.yaml
      - name: verify deployment
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#          KUBECTL_VERSION: "1.23"
        with:
          args: rollout status deployment/my-app
